# action.yml
name: 'Stark Accessibility Checker'
description: "Run your server on github's infra and scan for accessibility issues with Stark's tooling"
branding:
  icon: 'code'
  color: 'purple'
inputs:
  setup: # set up the container
    description: 'Set up the current container. Here you can install dependencies related to the container. E.g. install a node version. Use the node version.'
    required: false
    default: 'echo "Nothing to setup"'
  prebuild: # install project dependencies
    description: 'Install project dependencies. E.g. npm install'
    required: false
    default: 'echo "Nothing to prebuild"'
  build: # build the project
    description: 'Build the project. E.g npm build'
    required: false
    default: 'echo "Nothing to build"'
  serve: # serve the project on localhost
    description: 'Serve the project. E.g npm start'
    required: false
    default: 'echo "Nothing to serve"'
  cleanup:
    description: 'Run a cleanup if needed.'
    required: false
    default: 'echo "Nothing to cleanup"'
  disable_ferryman:
    description: 'Enable ferryman on the scanner for optimised scans'
    required: false
    default: false
  urls:
    description: 'A list of URLs to be scanned, with each URL belonging to its own line. This value follows YAML conventions for multiline strings.'
    required: true
    default: 'https://getstark.co'
  wait_time:
    description: 'Time in milliseconds to wait before running the scanner. A rough time delay for your server to start'
    required: false
    default: 5000
  min_score:
    description: 'Minimum score for the action to pass. A number from 0 to 100'
    required: false
    default: 0
  token:
    description: "Stark token required to send data back to stark web. The cli doesn't post data if token is not provided"
    required: false
  puppeteer_timeout:
    description: 'Navigation timeout for puppeteer in ms'
    required: false
    default: 30000
  puppeteer_wait_until:
    description: 'Wait until params for puppeteer from [load, domcontentloaded, networkidle0, networkidle2]. Each value belongs to a new line. Follows YAML conventions.'
    required: false
    default: 'load'
  stealth_mode:
    description: "Run puppeteer in stealth mode. Attempts to hide puppeteer from your server. Won't be necessary for localhost"
    required: false
    default: false
  skip_errors:
    description: 'Continue to scanning the next url if an error occurs while scanning a url'
    required: false
    default: false
  scan_delay:
    description: 'Delay running a scan after navigation has completed (wait for something to happen on the page)'
    required: false
    default: 100
  viewport:
    description: 'Puppeteer browser viewport [width]x[height]'
    required: false
    default: '800x600'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.setup }}
    - ${{ inputs.prebuild }}
    - ${{ inputs.build }}
    - ${{ inputs.serve }}
    - ${{ inputs.cleanup }}
    - ${{ inputs.urls }}
    - ${{ inputs.min_score }}
    - ${{ inputs.wait_time }}
    - ${{ inputs.token }}
    - ${{ inputs.viewport }}
